### DISCUSSION TITLE
Docker Compose

### DISCUSSION THREAD

**Discussion by kruzikt** [canarytrace/documentation#183] [RUM] [answered]
Hello, Nowadays we don't use Kubernetes and we would like to run Canarytrace RUM service in docker swarm.
Is there docker compose file available for this? Thanks a lot.

**Comment by rdpanek** [comment, marked as answer]
Hi @kruzikt 
we use this docker-compose for local development. You can use this for your case :)
```yaml
version: '3'

services:
  nginx:
    image: nginx:1.23.1
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certificates:/ssl/
  rum:
    image: quay.io/canarytrace/rum:dev
    container_name: rum
    restart: unless-stopped
    ports:
      - 3000:3000
    expose:
      - 3000
    environment:
      - ELASTIC_CLUSTER=$ELASTIC_CLUSTER
      - ELASTIC_HTTP_AUTH=$ELASTIC_HTTP_AUTH
```
