### ISSUE TITLE
Kubernetes and deployments

### ISSUE THREAD

**Issue by rdpanek** [canarytrace/documentation#114]
Create a Deployments for Kubernetes

- [x] Create kind Deployment
- [x] Create kind Service
- [x] Create kind Secret
- [x] Resource recommendation
- [x] ACC: describe how to work or small documentation into this ticket

**Comment by rdpanek** [comment]
# Kubernetes
Canarytrace RUM is ready for run in Kubernetes. You must create configuration objects in Kubernetes.

## How to get Deployment scripts

```yaml
docker run --rm -it --entrypoint /bin/mv -v $(pwd):/deployments quay.io/canarytrace/rum:1.10 /opt/canary-rum/deployments/ /deployments/
```
This command move directory `deployments` from Docker container to localhost.

- `secret.yaml` contains Elasticsearch credentials and licence
- `nginx-config.yaml` contains configuration for Nginx
- `deployment.yaml` configuration for RUM

## Secret
Create secret and fill `elastic.cluster`, `elastic.http.auth` and `license`

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: canarytrace-secret
  namespace: canarytrace
type: Opaque
stringData:
  elastic.cluster: ""
  elastic.http.auth: "elastic:XYZ"
  license: ""
```

## Secret with ssl certificates
You must create secret with ssl keys if you use http2

`kubectl -n canarytrace create secret generic rum-crt --from-file=crt=./certificates/rum_canarytrace_com.crt --from-file=privkey=./certificates/rum_privkey.pem`

## Nginx
Rum use Nginx for functions gzip, https and http/2. You must deploy configuration for Nginx into Kubernetes.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: rum-nginx-config
  namespace: canarytrace
data:
  config: |
    events { }

    http {
      gzip on;
      gzip_comp_level 6;
      gzip_vary on;
      gzip_types text/plain text/css application/json application/x-javascript application/javascript text/xml application/xml application/rss+xml text/javascript image/svg+xml application/vnd.ms-fontobject application/x-font-ttf font/opentype;

      server {
        listen 80;
        server_name localhost;
        return 301 https://localhost$request_uri;
      }

      keepalive_timeout  65;

      server {
        listen 443 ssl http2;
        server_name localhost;

        ssl_certificate /ssl/crt;
        ssl_certificate_key /ssl/privkey;
        
        access_log /var/log/nginx/data-access.log combined;

        add_header Access-Control-Allow-Origin *;

        location / {
          proxy_pass http://localhost:3000/;
          proxy_set_header X-Real-IP  $remote_addr;
          proxy_set_header X-Forwarded-For $remote_addr;
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_redirect http://localhost:3000/ $scheme://$http_host/;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_read_timeout 20d;
          proxy_buffering off;
        }
      }
    }
```

## Deployment

Please, always use a latest docker image e.g. `quay.io/canarytrace/rum:1.10`. You can found latest docker images on this page https://quay.io/repository/canarytrace/rum?tab=tags

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rum
  namespace: canarytrace
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rum
  template:
    metadata:
      labels:
        name: rum
    spec:
      containers:
      - name: rum
        image: quay.io/canarytrace/rum:1.10
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000
        env:
        - name: LABELS
          value: "rum"
        - name: ELASTIC_CLUSTER
          valueFrom:
            secretKeyRef:
              name: canarytrace-secret
              key: elastic.cluster
        - name: ELASTIC_HTTP_AUTH
          valueFrom:
            secretKeyRef:
              name: canarytrace-secret
              key: elastic.http.auth
        resources:
          requests:
            memory: "300Mi"
            cpu: "100m"
          limits:
            memory: "800Mi"
            cpu: "500m"
      - name: nginx
        image: nginx:1.23.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: rum-crt
          readOnly: true
          mountPath: "/ssl/"
        - name: rum-nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: config
          readOnly: true
        ports:
          - containerPort: 443
        resources:
          requests:
            memory: "300Mi"
            cpu: "100m"
          limits:
            memory: "800Mi"
            cpu: "500m"
      volumes:
        - name: canarytrace-secret
          secret:
            secretName: secret
        - name: rum-crt
          secret:
            secretName: rum-crt
        - name: rum-nginx-config
          configMap:
            name: rum-nginx-config
            items:
              - key: config
                path: config
```

## Services
Object for exposing your Canarytrace RUM endpoints. You get an External IP.

```yaml
apiVersion: v1
kind: Service
metadata:
  name: rum
  namespace: canarytrace
spec:
  type: LoadBalancer
  ports:
  - name: https
    port: 443
    targetPort: 443
  selector:
    name: rum
```

Now is your RUM ready 👌
