### ISSUE TITLE
Kubernetes and Deployments

### ISSUE THREAD

**Issue by rdpanek** [canarytrace/documentation#123]
Create a Deployments for Kubernetes

- [x] Create kind CronJob
- [x] ACC: describe how to work or small documentation into this ticket

**Comment by rdpanek** [comment]
# Kubernetes
Canarytrace RUM is ready for run in Kubernetes. You must create configuration objects in Kubernetes.

## How to get Deployment scripts

```yaml
docker run --rm -it --entrypoint /bin/mv -v $(pwd):/deployments quay.io/canarytrace/dm:1.3 /opt/data-management/deployments/ /deployments/
```
This command move directory `deployments` from Docker container to localhost.

- `secret.yaml` contains Elasticsearch credentials and licence
- `deployment.yaml` CronJob for Data Management
- `rollup_config.yaml` Configuration for rollup jobs

## Secret
Create secret and fill `elastic.cluster` and `elastic.http.auth`

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: canarytrace-secret
  namespace: canarytrace
type: Opaque
stringData:
  elastic.cluster: ""
  elastic.http.auth: "elastic:XYZ"
```

## Deployment

Please, always use a latest docker image e.g. `quay.io/canarytrace/dm:1.3`. You can found latest docker images on this page https://quay.io/repository/canarytrace/dm?tab=tags

```yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: data-management
  namespace: canarytrace
spec:
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 2
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: data-management
            image: quay.io/canarytrace/dm:1.3
            env:
            - name: CREATE_TRENDS
              value: "allow"
            - name: DATA_RETENTION_DAYS
              value: "14"
            - name: ELASTIC_CLUSTER
              valueFrom:
                secretKeyRef:
                  name: canarytrace-secret
                  key: elastic.cluster
            - name: ELASTIC_HTTP_AUTH
              valueFrom:
                secretKeyRef:
                  name: canarytrace-secret
                  key: elastic.http.auth
            resources:
              requests:
                memory: "100Mi"
                cpu: "100m"
              limits:
                memory: "200Mi"
                cpu: "800m"
            imagePullPolicy: "IfNotPresent"
            volumeMounts:
              - name: data-management-rollup
                mountPath: /opt/data-management/rollup_jobs/report.json
                subPath: report.json
                readOnly: true
              - name: data-management-rollup
                mountPath: /opt/data-management/rollup_jobs/audit.json
                subPath: audit.json
                readOnly: true
              - name: data-management-rollup
                mountPath: /opt/data-management/rollup_jobs/request-log.json
                subPath: request-log.json
                readOnly: true
              - name: data-management-rollup
                mountPath: /opt/data-management/rollup_jobs/rum.metrics.json
                subPath: rum.metrics.json
                readOnly: true
          restartPolicy: "Never"
          terminationGracePeriodSeconds: 5
          volumes:
            - name: canarytrace-secret
              secret:
                secretName: secret
            - name: data-management-rollup
              configMap:
                name: data-management-rollup
                items:
                  - key: report.json
                    path: report.json
                  - key: audit.json
                    path: audit.json
                  - key: request-log.json
                    path: request-log.json
                  - key: rum.metrics.json
                    path: rum.metrics.json
```

**Environment variables**
- `DATA_RETENTION_DAYS` default is 14 days. You can change this.
- `ENV_PRINT` print all environment variables. Please remove if you do not need. 

## Rollup jobs configuration
Configuration for creating rollup jobs for create indices with trends. Older indices (with detailed data) will be deleted by Data Management, so you need rollup jobs for migration some metrics into indices with long live.

Default configuration https://github.com/canarytrace/documentation/issues/126

Now is your Data Management ready 👌
