### ISSUE TITLE
Upgrade: Google Chrome on latest version

### ISSUE THREAD

**Issue by rdpanek** [canarytrace/documentation#129]
- [x] Upgrade Google Chrome from 98 to 108, changes https://chromium.googlesource.com/chromium/src.git/+log/cbadbe267bec5c3c673d5a2f2fdef15541f5bfc1..4979aeac5db0ccb0efae4b892fd6bb3365e19228?n=1000&pretty=fuller
- [x] Upgrade K8s deployment script

**Comment by rdpanek** [comment]
All deployment scripts was upgraded `smoke-desktop-shipper.yaml`, `smoke-desktop.yaml`, `smoke-mobile.yaml` and `user-journey.yaml`

Copy k8s deployments from Docker container to your localhost.

```bash
docker run --rm -it --entrypoint /bin/mv -v $(pwd):/deployments quay.io/canarytrace/canarytrace-pub:<your-docker-image> /opt/canary/deployments/ /deployments/
```

example:
```yaml
 - name: selenium
            image: selenium/standalone-chrome:4.7.2-20221219
            ports:
              - containerPort: 4444
            resources:
              requests:
                memory: "2000Mi"
                cpu: "2000m"
              limits:
                memory: "4000Mi"
                cpu: "4000m"
            imagePullPolicy: "IfNotPresent"
```
