### ISSUE TITLE
Rules

### ISSUE THREAD

**Issue by rdpanek** [canarytrace/documentation#144]
Rules are collections/checklist of thresholds and other rules about quality of your web application. The Listener by these rules automatically check data downloaded from Canarytrace and RUM and compare them with conditions of each rule.

Each rule contains a reporters too. A reporters are targets for sending a notification about problems finding by Listener.
If a Listener found some problems in the analyzed data, automatically send one of more type notification by score defined in a each rule.

Listener work with three types of rules `interna-check`, `internal-rules` and `custom-rules`.

**Comment by rdpanek** [comment]
## Type `range`

This type of rule is ideal for evaluating thresholds. Filters contains operators`gt`, `gte`, `lt` and `lte` and you can use this for evaluating min and max thresholds.

```yaml
  - type: range
    title: "Load time needs improvement"
    index: c.performance-entries
    filter:
    - field: 'loadEventEnd'
      operator: 'gte'
      value: 3000
    - field: 'loadEventEnd'
      operator: 'lt'
      value: 5000
    min: 5
    score: 40
    reportLabels:
    - 'loadEventEnd'
    - 'timestamp'
    reporters:
    - type: slack
      message: "Page is complete loaded."
```

- `index` is source index in Elasticsearch.
- `min` defines a count of minimal occurrence. 
- `score` define impact on a real user from 0 = much poor to 100 percent = excellent.
- `reportLabes` are labels stored by each record in a Elasticsearch. These values will be stored in a `events` index. Labels help you defined source data.
- `reporters` is target for sending message.

The rule analyzer of a Listener create this Elasticsearch query:
```json
{
  "_source": [
    "uuid",
    "_id",
    "loadEventEnd",
    "timestamp"
  ],
  "query": {
    "bool": {
      "filter": [
        {
          "range": {
            "loadEventEnd": {
              "gte": 3000
            }
          }
        },
        {
          "range": {
            "loadEventEnd": {
              "lt": 5000
            }
          }
        }
      ],
      "must": [
        {
          "range": {
            "timestamp": {
              "gte": "2022-12-11T21:16:50.802Z"
            }
          }
        }
      ]
    }
  },
  "sort": [
    {
      "timestamp": "desc"
    }
  ]
}
```

**Comment by rdpanek** [comment]
## Type `match`

This type of rule is ideal for finding some string in a label. 

```yaml
  - type: match
    title: "Failed check your page!"
    index: c.report
    field: passed
    operator: must
    expected: false
    min: 2
    score: 10
    reportLabels:
    - 'fullTitle'
    - 'timestamp'
    reporters:
    - type: slack
      message: "An error occurred while checking."
```

- `index` is source index in Elasticsearch.
- `min` defines a count of minimal occurrence. 
- `score` define impact on a real user from 0 = much poor to 100 percent = excellent.
- `reportLabes` are labels stored by each record in a Elasticsearch. These values will be stored in a `events` index. Labels help you defined source data.
- `reporters` is target for sending message.

The rule analyzer of a Listener create this Elasticsearch query:
```json
{
  "_source": [
    "uuid",
    "timestamp",
    "passed",
    "fullTitle",
    "timestamp"
  ],
  "query": {
    "bool": {
      "must": [
        {
          "range": {
            "timestamp": {
              "gte": "2022-12-11T23:06:09.977Z"
            }
          }
        },
        {
          "match": {
            "passed": false
          }
        }
      ]
    }
  },
  "sort": [
    {
      "timestamp": "desc"
    }
  ]
}
```

**Comment by rdpanek** [comment]
## Type `contains`

This type of rule is ideal for evaluating cases such as business metrics. Filters contains operators `gt`, `gte`, `lt` and `lte` and you can use this for evaluating min and max thresholds. You can also use an expressions.

```yaml
  - type: contains
    title: "Login to application."
    index: c.report
    field: fullTitle
    value: 'More steps and login login user'
    expression:
      field: 'event'
      operator: must
      values:
      - 'testStepEnd'
    filter:
    - field: 'testStepDuration'
      operator: 'gte'
      value: 1567
    min: 1
    score: 40
    reportLabels:
    - 'spec'
    - 'testStepDuration'
    reporters:
    - type: slack
      message: "Login to application not working."
```

- `index` is source index in Elasticsearch.
- `min` defines a count of minimal occurrence. 
- `score` define impact on a real user from 0 = much poor to 100 percent = excellent.
- `reportLabes` are labels stored by each record in a Elasticsearch. These values will be stored in a `events` index. Labels help you defined source data.
- `reporters` is target for sending message.

The rule analyzer of a Listener create this Elasticsearch query:
```json
{
  "_source": [
    "uuid",
    "timestamp",
    "fullTitle",
    "event",
    "spec",
    "testStepDuration"
  ],
  "query": {
    "bool": {
      "filter": [
        {
          "range": {
            "testStepDuration": {
              "gte": 1567
            }
          }
        }
      ],
      "must_not": [],
      "must": [
        {
          "range": {
            "timestamp": {
              "gte": "2022-12-12T00:00:32.165Z"
            }
          }
        },
        {
          "match": {
            "fullTitle": "More steps and login login user"
          }
        },
        {
          "match": {
            "event": "testStepEnd"
          }
        }
      ]
    }
  },
  "sort": [
    {
      "timestamp": "desc"
    }
  ]
}
```
