### ISSUE TITLE
Deployment & Kubernetes

### ISSUE THREAD

**Issue by rdpanek** [canarytrace/documentation#171]
The Listener agent is ready for run in Kubernetes. You must deploy configuration objects into Kubernetes for run.

👉 Always use latest Docker images, please check [our repository](https://quay.io/repository/canarytrace/listener-agent?tab=tags)

**Comment by rdpanek** [comment]
# step1: How to get k8s scripts

Copy k8s deployments from Docker container to your localhost.
`docker run --rm -it --entrypoint /bin/mv -v $(pwd):/k8s quay.io/canarytrace/listener-agent:1.42 /opt/canary-listener/k8s/ /k8s/`

**Kubernetes objects**
- `k8s/config-custom-rules.yaml` - yaml with your custom rules. E.g. max time to login to app.
- `k8s/config-internal-rules.yaml` - yaml with rules from us for evaluate data from Canarytrace.
- `k8s/config-rum-rules.yaml` - yaml with rules from us for evaluate data from RUM.
- `k8s/deployment.yaml` - listener-agent [CronJob](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/)
- `k8s/secret.yml` - listener-agent-secret please set the secret credentials for Elasticsearch and params for e-email.

**Comment by rdpanek** [comment]
# step2: Prepare and configuration
- Setup your secrets params in `k8s/secret.yaml` e.g. Elasticsearch, e-mail etc.
- You can run listener-agent with default settings`k8s/deployment.yaml`.
- If you want, you can change behavior or settings of the listener-agent via [environment variables ](https://github.com/canarytrace/documentation/issues/168)

**Comment by rdpanek** [comment]
# step3: Deployment and start
[Docker image](https://quay.io/repository/canarytrace/listener-agent?tab=tags) with listener-agent and deployment for k8s `k8s/deployment.yaml` contains a default configuration for immediately start.

👉 Please, always use the latest [Docker image](https://quay.io/repository/canarytrace/listener-agent?tab=tags) image with listener-agent.

---

## Two strategies

**We don't want make any change in the build-in rules**
- Remove listed below from `k8s/deployment.yaml` because [Docker image](https://quay.io/repository/canarytrace/listener-agent?tab=tags) with listener-agent contain build-in rules definitions.
- You don't must upload config files `k8s/config-custom-rules.yaml`, `k8s/config-internal-rules.yaml` and `k8s/config-rum-rules.yaml` in this case.

1). Deploy `k8s/secret.yaml`
2). Deploy `k8s/deployment.yaml`

```yaml
# remove from k8s/deployment.yaml
...
            volumeMounts:
              - name: config-internal-rules
                mountPath: /opt/canary-listener/rules/internal.yaml
                subPath: rules
                readOnly: true
              - name: config-custom-rules
                mountPath: /opt/canary-listener/rules/custom.yaml
                subPath: rules
                readOnly: true
              - name: config-rum-rules
                mountPath: /opt/canary-listener/rules/rum.yaml
                subPath: rules
                readOnly: true
...
            - name: config-internal-rules
              configMap:
                name: listener-agent-internal-rules
                items:
                  - key: rules
                    path: rules
            - name: config-custom-rules
              configMap:
                name: listener-agent-custom-rules
                items:
                  - key: rules
                    path: rules
            - name: config-rum-rules
              configMap:
                name: listener-agent-rum-rules
                items:
                  - key: rules
                    path: rules
```

**We want make our own lists of rules, or we want make changes in our custom rules**
- Edit [ConfigMaps](https://kubernetes.io/docs/concepts/configuration/configmap/) `k8s/config-custom-rules.yaml`, `k8s/config-internal-rules.yaml` and `k8s/config-rum-rules.yaml`  with rules by this manual https://github.com/canarytrace/documentation/issues/110

Deploy to k8s this objects in order:
1). `k8s/secret.yaml`
2). `k8s/config-custom-rules.yaml`
3). `k8s/config-internal-rules.yaml`
4). `k8s/config-rum-rules.yaml`
5). `k8s/deployment.yaml`
