### ISSUE TITLE
Listener: Automatic thresholds

### ISSUE THREAD

**Issue by rdpanek** [canarytrace/documentation#48]
# Idea

> Listener will be automatically search in Elasticsearch indices and look for opportunities for automated alerting by defined rules. 

- Canarytrace will supply set of rules by our recommendations https://github.com/canarytrace/documentation/issues/46
- User can define own rules

## Rules

- `range` - search on one index higher or lower values
- `match` - search on one index exactly expression
- `multi-match` - can combine `range` and `match` type of rules from more indices

## Mandatory params

All definition of rules must contains:

- **`type`** can be of type `range`, `match`, `multi-match`
- **`timeRange`** how old records will be evaluated
- **`reporter`** what type of reporter will be triggered

### `range`

- `index` - in which index it will be searched
- `filed` - in which field in index will be searched value that is outside the threshold
- `operator` - can contains `gte` or `lte`
- `value` - expected value

Example:

```yaml
  - type: range
    description: ''
    index: c.report
    timeRange: now-1h
    field: testStepDuration
    operator: gte
    value: 1000
    reporter:
    - type: events
      min: 10
      nearby: 3
      score: 50
      message: 'description of threshold or recommended'
```      

### `match`

- `index` - in which index it will be searched
- `filed` - in which field in index will be searched value that is outside the threshold
- `operator` - can contains `must` or `must_not`
- `expected` - expected value

Example:

```yaml
  - type: match
    description: ''
    index: c.report
    timeRange: now-1h
    field: passed
    operator: must
    expected: false
    reporter:
    - type: events
      min: 10
      nearby: 3
      score: 50
      message: 'description of threshold or recommended'
```

### `multi-match`

- `matches` - collection of rules type `match` and / or `range`. Max. rules 4.

Example:

```yaml
  - type: multi-match
    description: ''
    timeRange: now-1h
    matches:
    -  type: range
       index: c.performance-entries
       field: responseTime
       operator: lte
       value: 1000
    -  type: match
       index: c.report
       field: sequence
       operator: must
       expected: 9
    reporter:
    - type: events
      score: 50
      message: 'description of threshold or recommended'
```

## Reporters

Reporter is method of alert

```yaml
    reporter:
    - type: events
      score: 50
      message: 'description of threshold or recommended'
```

`type` - can contains `events`, `slack`, `email`, ...
`score` - weight of the incident

**Optional parameters**

`min` - count of successive occurrences without interruption
`nearby` - count of minimum occurrence in the selected data set

**Comment by rdpanek** [comment]
# From which index will it be searched?

## speed metrics
- `c.performance-entries-*` -> [documentation](https://canarytrace.com/docs/features/live-reporting#cperformance-entries-)
- `c.audit-*` -> [documentation](https://canarytrace.com/docs/features/live-reporting#caudit-)

## responses and headers
- `c.respone` -> [documentation](https://canarytrace.com/docs/features/live-reporting#cresponse-)

## for Canarytrace Smoke Pro
- `c.smoke-title-*` - body of title element -> [documentation](https://canarytrace.com/docs/features/live-reporting#csmoke-title-)

## functional incidents / anomaly
- `c.report-*` -> [documentation](https://canarytrace.com/docs/features/live-reporting#creport-)

## memory usage exceeded
- `c.memory-*` -> [documentation](https://canarytrace.com/docs/features/live-reporting#cmemory-)

**Comment by rdpanek** [comment]
# Final structure of rules

### Rule `match`

- Get records in the last hour from `dev.report` index with condition `passed === false` 
- You can use operator `must` and `must_not`.
- `min` is optional

```yaml
  - type: match
    title: 'Functional defect'
    index: dev.report
    timeRange: now-1h
    field: passed
    operator: must
    expected: false
    min: 10
    reporter:
    - type: events
      score: 40
      message: 'Some of test step is not working.'
```

### `contains`

- Get records in the last hour from `dev.response` index and search documents with `headers.content-type == headers.content-encoding` which not contains values `gzip` or `br` in `headers.content-encoding` label
- You can use operator `must` and `must_not`
- All values in `values` labels are chained by operator, e.g. `NOT headers.content-encoding=gzip AND NOT headers.content-encoding=br`
- `min` is optional

```yaml
- type: contains
    title: 'JS content encoding must contains gzip or br'
    index: dev.response
    timeRange: now-1h
    field: headers.content-type
    value: 'application/javascript'
    expression:
      field: 'headers.content-encoding'
      operator: must_not
      values:
      - 'gzip'
      - 'br'
    min: 10
    reporter:
    - type: events
      score: 40
      message: 'JS missing encoding must contains gzip or br'
```

### `range`

- Get records in the last hour from `dev.performance-entries` index with condition `responseTime > 1000` 
- You can use operator `gte` and `lte`.
- `min` is optional

```yaml
  - type: range
    title: 'Higher response time'
    index: dev.performance-entries
    timeRange: now-1h
    field: responseTime
    operator: gte
    value: 1000
    min: 10
    reporter:
    - type: events
      score: 50
      message: 'Response time is higher than 1s'
```

## Full example
```yaml
rules:
  - type: match
    title: 'Functional defect'
    index: dev.report
    timeRange: now-1h
    field: passed
    operator: must
    expected: false
    min: 10
    reporter:
    - type: events
      score: 40
      message: 'Some of test step is not working.'
  - type: contains
    title: 'JS content encoding must contains gzip or br'
    index: dev.response
    timeRange: now-1h
    field: headers.content-type
    value: 'application/javascript'
    expression:
      field: 'headers.content-encoding'
      operator: must_not
      values:
      - 'gzip'
      - 'br'
    min: 10
    reporter:
    - type: events
      score: 40
      message: 'JS missing encoding must contains gzip or br'
  - type: range
    title: 'Higher response time'
    index: dev.performance-entries
    timeRange: now-1h
    field: responseTime
    operator: gte
    value: 1000
    min: 10
    reporter:
    - type: events
      score: 50
      message: 'Response time is higher than 1s'
 ```

**Comment by rdpanek** [comment]
# Score table and internal checks

> This table is used by internal checks

- `canaryIsLive` - check, that Canarytrace is run and send data to c.report index
- `heatlCheck` -  basic check of vitality of Elasticsearch. Report is fired when is status of elasticsearch cluster `yellow` or `red`. Report message show status of elastic plus count of pending tasks.
- `nodesCheck` - checks values on all nodes `heap.percent`, `ram.percent`, `disk.used_percent`, `cpu`. Report is fired when `heap.percent` is higher than 70% or `disk.used_percent` is higher than 85%

```javascript
const score = {
  // 0 - 30 poor
  poor: 0,

  // 31 - 70 needs improvement
  middle: 50,

  // 71 - 100 good
  good: 100
}
```

## Internal check score overview
| Internal check | Score | Description |
|-|-|-|
| ⚙️ Canarytrace is down | 0 | Canarytrace did not send data to `c.report-*` index |
| ⚙️ Elasticsearch health is yellow | 50 | Need improvements |
| ⚙️ Elasticsearch health is red | 0 | Elasticsearch is probably down |
| ⚙️ Java Heap is higher than 70% | 50 | Is close to overloaded and need improvements |
| ⚙️ Java Heap is higher than 85% | 50 | Elasticsearch nodes is overloaded |

## Reporting
If rule use type of reporter `events` are all results of internal checks stored in `c.listener-events-*` index
<img width="1623" alt="Snímek obrazovky 2021-02-25 v 11 01 50" src="https://user-images.githubusercontent.com/230124/109137141-2ca90080-7759-11eb-89dd-9cee347d54a9.png">

**Comment by rdpanek** [comment]
Final structure of rules + added support of multi reports (draft2)

**yaml with rules definition**
```yaml
rules:
  - type: match
    title: 'Functional defect'
    index: dev.report
    timeRange: now-1h
    field: passed
    operator: must
    expected: false
    min: 10
    reporters:
    - type: slack-internal
      score: 50
      message: Web isnt available
    - type: events
      score: 50
      message: Web isnt available
  - type: contains
    title: 'JS content encoding must contains gzip or br'
    index: dev.response
    timeRange: now-1h
    field: headers.content-type
    value: 'application/javascript'
    expression:
      field: 'headers.content-encoding'
      operator: must_not
      values:
      - 'gzip'
      - 'br'
    min: 10
    reporters:
    - type: slack-internal
      score: 50
      message: Response time is higher than 1s
    - type: events
      score: 50
      message: Web isnt available
  - type: range
    title: 'Higher response time'
    index: dev.performance-entries
    timeRange: now-1h
    field: responseTime
    operator: gte
    value: 1000
    min: 10
    reporters:
    - type: slack-internal
      score: 50
      message: Response time is higher than 1s
    - type: events
      score: 50
      message: Web isnt available
```

## `reporters`

Reporters can contains one or more reporters, so alert can be stored into elasticsearch index `c.listener-events-*` and can be send to slack

### Slack example
<img width="686" alt="Screenshot 2021-02-27 at 8 07 53" src="https://user-images.githubusercontent.com/230124/109378518-803f5980-78d3-11eb-9dce-e83c392dcc6b.png">

### `c.listener-events-*` example
<img width="1127" alt="Screenshot 2021-02-27 at 8 08 07" src="https://user-images.githubusercontent.com/230124/109378528-93eac000-78d3-11eb-89a6-3dc901355539.png">

One of record
```json

{
  "_index": "dev.listener.events-2021.02.27",
  "_type": "_doc",
  "_id": "dFpN4ncBG-y-MkzOsPYe",
  "_version": 1,
  "_score": null,
  "_source": {
    "type": "events",
    "rule": "cldr",
    "score": 50,
    "title": "Functional defect",
    "description": "Web isnt available total 36",
    "documents": [
      {
        "_index": "dev.report-2021-02-27",
        "_id": "v1pL4ncBG-y-MkzO8fXF"
      },
      {
        "_index": "dev.report-2021-02-27",
        "_id": "vFpL4ncBG-y-MkzO8fUd"
      },
      {
        "_index": "dev.report-2021-02-27",
        "_id": "uVpL4ncBG-y-MkzO8PV_"
      },
      {
        "_index": "dev.report-2021-02-27",
        "_id": "tlpL4ncBG-y-MkzO7_XZ"
      },
      {
        "_index": "dev.report-2021-02-27",
        "_id": "s1pL4ncBG-y-MkzO7_Un"
      },
      {
        "_index": "dev.report-2021-02-27",
        "_id": "sFpL4ncBG-y-MkzO7vWD"
      },
      {
        "_index": "dev.report-2021-02-27",
        "_id": "rVpL4ncBG-y-MkzO7fW8"
      },
      {
        "_index": "dev.report-2021-02-27",
        "_id": "p1pL4ncBG-y-MkzO7fUB"
      },
      {
        "_index": "dev.report-2021-02-27",
        "_id": "pFpL4ncBG-y-MkzO7PVA"
      },
      {
        "_index": "dev.report-2021-02-27",
        "_id": "oVpL4ncBG-y-MkzO6_WS"
      },
      {
        "_index": "dev.report-2021-02-27",
        "_id": "nlpL4ncBG-y-MkzO6vXU"
      },
      {
        "_index": "dev.report-2021-02-27",
        "_id": "m1pL4ncBG-y-MkzO6vUX"
      },
      {
        "_index": "dev.report-2021-02-27",
        "_id": "k1pL4ncBG-y-MkzOm_XQ"
      },
      {
        "_index": "dev.report-2021-02-27",
        "_id": "kFpL4ncBG-y-MkzOm_Ud"
      },
      {
        "_index": "dev.report-2021-02-27",
        "_id": "jVpL4ncBG-y-MkzOmvV6"
      },
      {
        "_index": "dev.report-2021-02-27",
        "_id": "ilpL4ncBG-y-MkzOmfXO"
      },
      {
        "_index": "dev.report-2021-02-27",
        "_id": "h1pL4ncBG-y-MkzOmfUt"
      },
      {
        "_index": "dev.report-2021-02-27",
        "_id": "hFpL4ncBG-y-MkzOmPWB"
      },
      {
        "_index": "dev.report-2021-02-27",
        "_id": "gVpL4ncBG-y-MkzOl_XP"
      },
      {
        "_index": "dev.report-2021-02-27",
        "_id": "flpL4ncBG-y-MkzOl_UZ"
      },
      {
        "_index": "dev.report-2021-02-27",
        "_id": "e1pL4ncBG-y-MkzOlvVq"
      },
      {
        "_index": "dev.report-2021-02-27",
        "_id": "eFpL4ncBG-y-MkzOlfWp"
      },
      {
        "_index": "dev.report-2021-02-27",
        "_id": "dVpL4ncBG-y-MkzOlfUB"
      },
      {
        "_index": "dev.report-2021-02-27",
        "_id": "clpL4ncBG-y-MkzOlPVC"
      },
      {
        "_index": "dev.report-2021-02-27",
        "_id": "zlpL4ncBG-y-MkzOHfSH"
      },
      {
        "_index": "dev.report-2021-02-27",
        "_id": "y1pL4ncBG-y-MkzOHPTe"
      },
      {
        "_index": "dev.report-2021-02-27",
        "_id": "yFpL4ncBG-y-MkzOHPQb"
      },
      {
        "_index": "dev.report-2021-02-27",
        "_id": "xVpL4ncBG-y-MkzOG_Ru"
      },
      {
        "_index": "dev.report-2021-02-27",
        "_id": "wlpL4ncBG-y-MkzOGvS2"
      },
      {
        "_index": "dev.report-2021-02-27",
        "_id": "v1pL4ncBG-y-MkzOGfT8"
      },
      {
        "_index": "dev.report-2021-02-27",
        "_id": "vFpL4ncBG-y-MkzOGfRM"
      },
      {
        "_index": "dev.report-2021-02-27",
        "_id": "uVpL4ncBG-y-MkzOGPSK"
      },
      {
        "_index": "dev.report-2021-02-27",
        "_id": "tlpL4ncBG-y-MkzOF_Sx"
      },
      {
        "_index": "dev.report-2021-02-27",
        "_id": "s1pL4ncBG-y-MkzOFvTn"
      },
      {
        "_index": "dev.report-2021-02-27",
        "_id": "sFpL4ncBG-y-MkzOFvQb"
      },
      {
        "_index": "dev.report-2021-02-27",
        "_id": "rVpL4ncBG-y-MkzOEfQR"
      }
    ],
    "timestamp": "2021-02-27T08:04:37+01:00"
  },
  "fields": {
    "timestamp": [
      "2021-02-27T07:04:37.000Z"
    ]
  },
  "sort": [
    1614409477000
  ]
}

**Comment by rdpanek** [comment]
## Dependencies
![dependencies](https://user-images.githubusercontent.com/230124/109378709-05773e00-78d5-11eb-87c5-98a67416ac61.png)

`madge --image docs/dependencies.png thresholdAnalyzer.js ` 👌

**Comment by rdpanek** [comment]
## Email sender / reporter

- nodemailer https://nodemailer.com/about/
- email-templates https://www.npmjs.com/package/email-templates

**Comment by rdpanek** [comment]
Final rules (draft2)

### Rules
All default rules are setup via ConfigMap `config-rules.yaml`, example:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: canarytrace-listener-rules
  namespace: canarytrace
data:
  rules: |
    rules:
    - type: match
      title: 'Failed check your page!'
      index: c.report
      timeRange: now-1h
      field: passed
      operator: must
      expected: false
      min: 2
      reportLabels:
      - 'fullTitle'
      - 'timestamp'
      reporters:
      - type: slack
        score: 10
        message: An error occurred while checking.
      - type: events
        score: 10
        message: An error occurred while checking.
      - type: email
        score: 10
        message: An error occurred while checking.
        recipients:
        - 'rdpanek@canarytrace.com'
    - type: contains
      title: 'JS content encoding must contains gzip or brotli compression'
      index: c.response
      timeRange: now-1h
      field: headers.content-type
      value: 'javascript'
      expression:
        field: 'headers.content-encoding'
        operator: must_not
        values:
        - 'gzip'
        - 'br'
      min: 10
      reportLabels:
      - 'url'
      - 'timestamp'
      reporters:
      - type: slack
        score: 40
        message: Use Brotli for plain text compression.
      - type: events
        score: 40
        message: Use Brotli for plain text compression.
    - type: contains
      title: 'CSS content encoding must contains gzip or brotli compression'
      index: c.response
      timeRange: now-1h
      field: headers.content-type
      value: 'css'
      expression:
        field: 'headers.content-encoding'
        operator: must_not
        values:
        - 'gzip'
        - 'br'
      min: 10
      reportLabels:
      - 'url'
      - 'timestamp'
      reporters:
      - type: slack
        score: 40
        message: Use Brotli for plain text compression.
      - type: events
        score: 40
        message: Use Brotli for plain text compression.
    - type: range
      title: 'Higher response time'
      index: c.performance-entries
      timeRange: now-1h
      field: responseTime
      operator: gte
      value: 3000
      min: 10
      reportLabels:
      - 'name'
      - 'responseTime'
      - 'timestamp'
      reporters:
      - type: slack
        score: 40
        message: Minimize server response time.
      - type: events
        score: 40
        message: Minimize server response time.
```

### Score table
Score table is definition default scores and colors
```javascript
const score = {
  // 0 - 30 poor
  poor: {
    value: 0,
    min: 0,
    max: 30,
    color: 'FA321C',
    description: 'needs fix'
  },

  // 31 - 70 needs improvement
  middle: {
    value: 50,
    min: 31,
    max: 70,
    color: 'FAA71C',
    description: 'needs improvement'
  },

  // 71 - 100 good
  good: {
    value: 100,
    min: 71,
    max: 100,
    color: '5FD963',
    description: 'congratulations, your service is good'
  }
}
```
