### ISSUE TITLE
Listener: Reporter: slack

### ISSUE THREAD

**Issue by rdpanek** [canarytrace/documentation#54]
## Reporter: slack
This reporter send mini report to into any slack

- `events` - save events, alert messaage and additional information to `c.listener-events-*`
- `slack` - send events and additional information to slack channel by `SLACK_WEBHOOK_URL`
- `slack-internal` - send events and additional information tocanarytrace slack channel `listener-events`

```yaml
    rules:
    - type: match
      title: 'Failed check your page!'
      index: c.report
      timeRange: now-1h
      field: passed
      operator: must
      expected: false
      min: 2
      reportLabels:
      - 'fullTitle'
      - 'timestamp'
      reporters:
      - type: slack
        score: 10
        message: An error occurred while checking.
      - type: slack-internal
        score: 10
        message: An error occurred while checking.
```

## Example mini report from internal checks

<img width="671" alt="Screenshot 2021-03-05 at 19 23 06" src="https://user-images.githubusercontent.com/230124/110157586-a50e6200-7de8-11eb-8772-f1522d9362a3.png">

## Example mini report from default rules

<img width="678" alt="Screenshot 2021-03-05 at 19 22 42" src="https://user-images.githubusercontent.com/230124/110157681-c53e2100-7de8-11eb-91e3-04a14de69079.png">
