### ISSUE TITLE
Listener: Reporter: Email

### ISSUE THREAD

**Issue by rdpanek** [canarytrace/documentation#55]
## Email sender / reporter

Email sender is reporter, which send email notification when is threshold is exceeded.

### Definition reporter

```yaml
rules:
  - type: match
    title: 'Functional defect'
    index: c.report
    timeRange: now-1h
    field: passed
    operator: must
    expected: false
    min: 10
    reportLabels:
    - 'fullTitle'
    - 'timestamp'
    reporters:
    - type: email
      score: 50
      message: Web isnt available
      recipients:
      - 'rdpanek@canarytrace.com'
      - 'miroslav.kret@canarytrace.com'
```

### Tools

- nodemailer https://nodemailer.com/about/
- email-templates https://www.npmjs.com/package/email-templates
