### ISSUE TITLE
Compare resources for one instance of Canarytrace Smoke Pro

### ISSUE THREAD

**Issue by rdpanek** [canarytrace/documentation#56]
# Compare resources
The browser needs more resources to make the measurement correct. 

Questions:
- What is the minimum.
- What is the behavior of loading page and how the lighthouse measures if the resources is very low?

Resources:
- https://canarytrace.com/docs/guides/kubernetes#required-resources-for-one-instance
- How to use task manager howtogeek.com/437681/how-to-use-chromes-built-in-task-manager
- How to use task manager https://www.techrepublic.com/article/how-to-take-control-of-chrome-with-its-very-own-task-manager/
- Minimum 2 dedicated cores (4 recommended)
- Minimum 2GB RAM (4-8GB recommended)

## Plan
- two web application, static and dynamic. 
- run test from two locations, from czech republic on standard home internet and from FRA1 region (AWS)
- configuration will be change every day

## Cronjob setup and performance audit setup
- smoke-desktop                */3 * * * * , desktopDense4G
- smoke-mobile                  */3 * * * *, mobileSlow4G

## Landing pages
- dynamic: http://edalnice.cz
- static: https://canarytrace.com

## Goals
- What is correct setup resources for one instance of Canaryrace?
- Exist some useful cases when is allocate very small resources for one instance of Canarytrace?

## Day1
Setup resources for browser for one instance.
```yaml
resources:
  requests:
    memory: "4000Mi"
    cpu: "2000m"
  limits:
    memory: "6000Mi"
    cpu: "4000m"
```

## Day2
Setup resources for browser for one instance.
```yaml
resources:
  requests:
    memory: "4000Mi"
    cpu: "2000m"
  limits:
    memory: "4000Mi"
    cpu: "2000m"
```

## Day3
Setup resources for browser for one instance.
```yaml
resources:
  requests:
    memory: "2000Mi"
    cpu: "2000m"
  limits:
    memory: "3000Mi"
    cpu: "2000m"
```

## Day4
Setup resources for browser for one instance.
```yaml
resources:
  requests:
    memory: "1000Mi"
    cpu: "1500m"
  limits:
    memory: "2000Mi"
    cpu: "1500m"
```

## Day5
Setup resources for browser for one instance.
```yaml
resources:
  requests:
    memory: "1000Mi"
    cpu: "1000m"
  limits:
    memory: "1500Mi"
    cpu: "1000m"
```

**Comment by rdpanek** [comment]
# DAY 1
> 07.03.2020 11h

Resources
```yaml
resources:
  requests:
    memory: "4000Mi"
    cpu: "2000m"
  limits:
    memory: "6000Mi"
    cpu: "4000m"
```

**Comment by rdpanek** [comment]
# Day2

Upgrade docker image on `3.0.6`

**Comment by rdpanek** [comment]
# Da1 `24.03.2021 20:00`

```yaml
resources:
  requests:
    memory: "4000Mi"
    cpu: "2000m"
  limits:
    memory: "6000Mi"
    cpu: "4000m"
```

**Comment by rdpanek** [comment]
#Day2 `25.03.2021 21:37`

```yaml
resources:
  requests:
    memory: "4000Mi"
    cpu: "2000m"
  limits:
    memory: "4000Mi"
    cpu: "2000m"
```

**Comment by rdpanek** [comment]
# Day3 `27.03.2021 22:50`

```yaml
resources:
  requests:
    memory: "2000Mi"
    cpu: "2000m"
  limits:
    memory: "3000Mi"
    cpu: "2000m"
```

**Comment by rdpanek** [comment]
# Day3 29.03.2021 23:01

```yaml
resources:
  requests:
    memory: "1000Mi"
    cpu: "1500m"
  limits:
    memory: "2000Mi"
    cpu: "1500m"
```

**Comment by rdpanek** [comment]
# Day5 01.04.2021 00:00

```yaml
resources:
  requests:
    memory: "1000Mi"
    cpu: "1000m"
  limits:
    memory: "1500Mi"
    cpu: "1000m"
```

**Comment by rdpanek** [comment]
# Day1 KOS `20.03.2021 00:50`

```yaml
resources:
  requests:
    memory: "4000Mi"
    cpu: "2000m"
  limits:
    memory: "6000Mi"
    cpu: "4000m"
```
---
### smoke overview

`fra1`
<img width="1386" alt="Screenshot 2021-04-21 at 0 10 26" src="https://user-images.githubusercontent.com/230124/115470157-2a819080-a236-11eb-8fcf-db09b9205dc3.png">


---
### performance audit / desktop

`fra1`
<img width="1386" alt="Screenshot 2021-04-21 at 0 11 01" src="https://user-images.githubusercontent.com/230124/115470174-32d9cb80-a236-11eb-95e6-203d37762aa0.png">

**Comment by rdpanek** [comment]
Day3 KOS 21.0342021 00:14

```yaml
resources:
  requests:
    memory: "2000Mi"
    cpu: "2000m"
  limits:
    memory: "3000Mi"
    cpu: "2000m"
```

**Comment by rdpanek** [comment]
# Day3 KOS 21.0342021 00:14

```yaml
resources:
  requests:
    memory: "2000Mi"
    cpu: "2000m"
  limits:
    memory: "3000Mi"
    cpu: "2000m"
```

**Comment by rdpanek** [comment]
# Day4 27.04.2021 21:07

```yaml
resources:
  requests:
    memory: "1000Mi"
    cpu: "1500m"
  limits:
    memory: "2000Mi"
    cpu: "1500m"
```

**Comment by rdpanek** [comment]
# Day5 02.05.2021 23:08

```yaml
resources:
  requests:
    memory: "1000Mi"
    cpu: "1500m"
  limits:
    memory: "2000Mi"
    cpu: "1500m"
```

---
### smoke overview

`fra1`




---
### performance audit / desktop

`fra1`

**Comment by rdpanek** [comment]
# Day6 03.05.2021 21:00
```
resources:
  requests:
    memory: "2000Mi"
    cpu: "2000m"
  limits:
    memory: "3000Mi"
    cpu: "2000m"
```
