### ISSUE TITLE
Storage for assets

### ISSUE THREAD

**Issue by rdpanek** [canarytrace/documentation#60]
Storage for assets / attachments for investigation e.g. static files from lighthouse https://github.com/canarytrace/documentation/issues/59

- [x] POC AWS S3
- [x] Store assets on Kubernetes PVC
- [x] Measure free space on PVC and set alerting via rules (listerner)
- [x] Remove data older than X days

**Comment by rdpanek** [comment]
## PVC on DigitalOcean (DO)

- DO contains only `do-block-storage` storage class https://kubernetes.io/docs/concepts/storage/persistent-volumes/
- DO support only `accessModes = ReadWriteOnce`
  - https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes
  - error: **Multi-Attach error for volume "pvc-d617f552-f953-4d30-b523-5f8b9ea8c83e" Volume is already used by pod(s) smoke-desktop-1617461640-mjcdw**

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: canarytrace-assets
  namespace: canary
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 35Gi
```
