### ISSUE TITLE
Kubernetes: add secret

### ISSUE THREAD

**Issue by rdpanek** [canarytrace/documentation#99]
**Goal**

Use secrets for deployments. It’s useful for deploy more instances.

**Comment by rdpanek** [comment]
**Download `secret.yaml` from Canarytrace docker image** 

`docker run --rm -it --entrypoint /bin/mv -v $(pwd):/deployments quay.io/canarytrace/canarytrace-pub:4.21.6-pro-20220222144833-79 /opt/canary/deployments/ /deployments/`

:warning: You must use your own Docker image with Canarytrace

**Secret**
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: canarytrace-secret
  namespace: canarytrace
type: Opaque
stringData:
  elastic.cluster: ""
  elastic.http.auth: "elastic:XYZ"
  license: ""
```

**CronJob**
```yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: smoke-desktop
  namespace: canarytrace
spec:
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 2
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: canarytrace
            image: <your-canarytrace-docker-image>
            env:
            - name: BASE_URL
              value: "https://webperf.canarytrace.com/;https://battle.canarytrace.com/"
            - name: PT_AUDIT
              value: "allow"
            - name: PT_AUDIT_THROTTLING
              value: "desktopDense4G"
            - name: LABELS
              value: "desktop, smoke"
            - name: LICENSE
              valueFrom:
                secretKeyRef:
                  name: canarytrace-secret
                  key: license
            - name: ELASTIC_CLUSTER
              valueFrom:
                secretKeyRef:
                  name: canarytrace-secret
                  key: elastic.cluster
            - name: ELASTIC_HTTP_AUTH
              valueFrom:
                secretKeyRef:
                  name: canarytrace-secret
                  key: elastic.http.auth
            resources:
              requests:
                memory: "300Mi"
                cpu: "200m"
              limits:
                memory: "1600Mi"
                cpu: "800m"
            volumeMounts:
              - name: assets
                mountPath: /opt/canary/assets
            imagePullPolicy: "IfNotPresent"
          - name: chrome
            image: selenium/standalone-chrome:4.1.1-20211217
            ports:
              - containerPort: 4444
            resources:
              requests:
                memory: "2000Mi"
                cpu: "2000m"
              limits:
                memory: "4000Mi"
                cpu: "4000m"
            imagePullPolicy: "IfNotPresent"
            volumeMounts:
              - mountPath: "/dev/shm"
                name: "dshm"
            livenessProbe:
              httpGet:
                path: /status
                port: 4444
              initialDelaySeconds: 10
              timeoutSeconds: 5
            readinessProbe:
              httpGet:
                path: /status
                port: 4444
              initialDelaySeconds: 10
              timeoutSeconds: 5
          restartPolicy: "Never"
          terminationGracePeriodSeconds: 5
          volumes:
            - name: "dshm"
              emptyDir:
                medium: "Memory"
            - name: "assets"
              emptyDir: {}
            - name: canarytrace-secret
              secret:
                secretName: secret
```
